version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx/.
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs/:/var/log/nginx/
  shinyproxy:
    # image: openanalytics/shinyproxy
    # image: openanalytics/shinyproxy-snapshot
    build:
      context: ./shinyproxy/.
    restart: unless-stopped
    depends_on:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./shinyproxy/application.yml:/opt/shinyproxy/application.yml
      - ./shinyproxy/logs/:/opt/shinyproxy/logs/
    ports:
      - 8080:8080
  app_basic:
    container_name: app_basic
    platform: linux/amd64
    stdin_open: true
    depends_on:
      - shinyproxy
    build:
      context: ./apps/basic/.
    expose:
      - 3838
  app_hello:
    container_name: app_hello
    platform: linux/amd64
    stdin_open: true
    depends_on:
      - shinyproxy
    build:
      context: ./apps/hello/.
    expose:
      - 3838
# networks:
#   nginx-net:
#     driver: bridge
#   shinyproxy-net:
#     driver: bridge