version: '3'
services:
  # TODO add nginx service in front
  nginx:
    container_name: nginx
    build:
      context: ./nginx/.
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs/:/var/log/nginx/
    networks:
      - my-net
  shinyproxy:
    image: openanalytics/shinyproxy
    # image: openanalytics/shinyproxy-snapshot
    user: root:root
    hostname: shinyproxy
    restart: unless-stopped
    depends_on:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./shinyproxy/application.yml:/opt/shinyproxy/application.yml
    ports:
      - 8080:8080
  app_basic:
    container_name: app_basic
    platform: linux/amd64
    #image: openstat_app_basic:230413
    build:
      context: ./app/basic/.
    networks:
      - my-net
    expose:
      - 3838
networks:
  my-net:
    name: my-net