proxy:
  title: Shiny App
  landing-page: /
  port: 8080
  container-log-path: /container-logs
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: tim
    password: password
  docker:
      internal-networking: true
      container-network: shinyproxy-net
  specs:
  # - id: 01_hello
  #   display-name: Hello Shiny App
  #   description: A simple reactive histogram
  #   container-cmd: ["R", "-e", "shiny::runApp('/home/app')"]
  #   container-image: registry.gitlab.com/analythium/shinyproxy-hello/hello:latest
  #   logo-url: https://github.com/analythium/shinyproxy-1-click/raw/master/digitalocean/images/app-hist.png
  #   access-groups: [admins, users]  
  - id: basic
    display-name: Basic App
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shiny::runApp('/root/basic')"] 
    container-image: app_basic
    container-network: "${proxy.docker.container-network}"

logging:
  file:
    name: logs/shinyproxy.log