proxy:
  title: Shiny App
  landing-page: /
  port: 8080
  container-log-path: /container-logs
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: tim
    password: password
  docker:
      internal-networking: true
      container-network: "docker_test_default"
  specs:
  - id: hello
    display-name: Hello Shiny App
    description: A simple reactive histogram
    container-cmd: ["R", "-e", "shiny::runApp('/home/app')"]
    container-image: docker_test-app_hello
    container-network: "${proxy.docker.container-network}"
    logo-url: https://github.com/analythium/shinyproxy-1-click/raw/master/digitalocean/images/app-hist.png
    access-groups: [admins, users]  
  - id: basic
    display-name: Basic App
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shiny::runApp('/root/basic', host = '0.0.0.0', port = 3838)"] 
    container-image: docker_test-app_basic
    container-network: "${proxy.docker.container-network}"

logging:
  file:
    name: logs/shinyproxy.log
    
server:
  servlet:
    context-path:  /